# Generated by Django 3.1.10 on 2022-02-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20210126_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='name',
        ),
        migrations.AddField(
            model_name='food',
            name='title',
            field=models.CharField(default=2, max_length=100, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(upload_to='foods/', verbose_name='تصویر'),
        ),
    ]
