# Generated by Django 3.1.10 on 2022-02-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('student_number', models.CharField(max_length=200, verbose_name='شماره ی دانشجویی')),
                ('phone', models.CharField(max_length=200, verbose_name='تلفن ')),
                ('Food_name', models.CharField(max_length=100, verbose_name='نام غذا')),
                ('number', models.IntegerField(verbose_name='تعداد')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('time', models.TimeField(verbose_name='ساعت')),
            ],
        ),
        migrations.DeleteModel(
            name='Reseravtion',
        ),
    ]
